name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.SSH_SERVER }}
        username: ${{ secrets.SSH_UNAME }}
        KEY: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
            whoami
            ls -al
