name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ***REMOVED***/defaced:latest
    - name: Login to the Docker hub
      run: docker login --username "***REMOVED***" --password "***REMOVED***"
    - name: push docker images
      run: docker push ***REMOVED***/defaced:latest
